# DataRoot University DS100 Test #2
На проходження тесту виділяється 87 хвилин.

## Python

### 1.  Реалізуйте функцію, яка повертає індекс кортежу, сума елементів якого є найменшою серед кортежів в списку:
У відповідь вивести результат роботи ф-ції для наступного списку:
```
[(10, 20), (1), (30, 56, 25), (10, 20), (33), (40), (200), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]
```


```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [4]:
l = [(10, 20), (1), (30, 56, 25), (10, 20), (33), (40), (200), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]
i = 0
j = 0
mint = sum(l[0])
for t in l:
    if type(t) == tuple:
        if sum(t) < mint:
            mint = sum(t)
            j = i
    else:
        if t < mint:
            mint = t
            j = i
    i+=1
print(j)

1


### 2.  Реалізуйте функцію str -> dict, таку, що ключем dict є слово, а значенням - його кількість в початковій str:
У відповідь вивести результат роботи ф-ції для наступної строки:
```"Text mining, also referred to as text data mining, roughly equivalent to text analytics, is the process of deriving high-quality information from text."```

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [7]:
string = "Text mining, also referred to as text data mining, roughly equivalent to text analytics, is the process of deriving high-quality information from text."
word_list = string.split(' ')
def str_to_dict(string):
    words_list = string.split(' ')
    words_dict = {}
    for idx,word in enumerate(words_list):
        words_dict[word]=idx
    return words_dict

print(str_to_dict(string))
    

{'information': 20, 'high-quality': 19, 'to': 11, 'process': 16, 'Text': 0, 'equivalent': 10, 'mining,': 8, 'text.': 22, 'roughly': 9, 'analytics,': 13, 'deriving': 18, 'also': 2, 'as': 5, 'of': 17, 'text': 12, 'from': 21, 'the': 15, 'data': 7, 'is': 14, 'referred': 3}


### 3. Спортсмен почав тренування, пробігши в перший день N км (N - ціле, N > 0). Кожен наступний день він зменшував дистанцію пробігу на Р відсотків від дистанції пробігу попереднього дня(Р - дійсне, 0 < P < 50) до тих пір, коли дистанція пробігу за день стане меншою, ніж N / R (R - ціле, 0 < R < N, N / R - дійсне), після цього дня спортсмен збільшує дистанцію пробігу на Р відсотків від дистанції пробігу попереднього дня, до тих пір, коли дистанція за день стане більшою, ніж N*R, після цього дня виконується початкове правило, тобто дистанція зменшується до N/R, а потім збільшується до N*R за вищеописаним циклічним законом. По заданим Р, N, M, R, визначити, після якого дня сумарний пробіг спортсмена за всі дні буде вперше більшим, ніж M км (М - ціле, M > N). Вивести знайдену кількість днів К (K - ціле) і сумарний пробіг за К днів.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 10хв
```

In [9]:
def culculate(n,p,r,m):
    sum_run = n
    day_run = n
    day = 1
    while True:
        if sum_run >= m:
            return day,sum_run
        if day_run < n/r:
            while day_run < n*r:
                if sum_run >= m:
                    return day,sum_run
                day_run += day_run*p/100
                sum_run += day_run
                day += 1
        else:
            day_run -= day_run*p/100
            sum_run += day_run 
            day += 1
print(culculate(10,40,2,50))


(7, 53)


### 4. Реалізуйте клас Sphere, який створюється за радіусом. Містить два методи, які повертають відповідно: площу поверхні та об'єм.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

In [17]:
import math
class Sphere(object):    
    def __init__(self,r):
        self.r = r
        
    def squere(self):
        return math.pi*4*self.r**2
    
    def volume(self):
        return 4/3*math.pi*self.r**3
    
s = Sphere(2)
print(s.squere(),s.volume())


(50.26548245743669, 25.132741228718345)


### 5.  Реалізуйте декоратор, який логує аргументи функцій та повернене значення кожного виклику. А при помилковому виклику відловлює та пише тип помилки. Необхідно виводити як позиційні(```*args```), так й іменовані аргументи(```**kwargs```):

Приклад застосування вашого декоратору в результаті:
```
>>> @log
... def func(*args):
...   return len(args) + sum(args)
>>> func(4, 4, 4)
You called func(4, 4, 4)
It returned 15
15

>>> func(4, 4, "4")
You called func(4, 4, "4")
It Raised TypeError
```

```
```
```
```
```
```
```
Максимальна оцінка: 4 бали
Рекомендований час: 12хв
```

In [21]:
def log(func):
    def func_wrapper(*args,**kargs):
        print("You called func({0},{1})".format(args,kargs))
        print("It returned {0}".format(func(*args,**kargs)))
    
    return func_wrapper
    
@log
def func(*args,**kargs):
    return len(args) + sum(args)

print(func(4,4,4))


You called func((4, 4, 4),{})
It returned 15
None


## Libraries: numpy, scipy, pandas, matplotlib

### Numpy

### 6. Дана матриця:
\begin{align}
A = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}


#### Відніміть середнє арифметичне кожного стовпчику від кожного елементу у відповідному стовпчику:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [37]:
import numpy as np
string = "17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\"
def string_to_list(string):
    lines = string.split('\\')
    list_of_numbers = []
    for line in lines:
        list_of_numbers.append(line.split('&'))
    int_list = []
    for line in list_of_numbers:
        if not line:
            continue
        int_line = []
        for elm in line:
            if not elm:
                continue
            int_line.append(int(elm))
        int_list.append(int_line)
    int_list = int_list[:-1]
    print(int_list)
    return int_list

int_list = string_to_list(string)

array = np.array(int_list)
print(array)
for col in array:
    avrege = sum(col)/len(col)
    col -=avrege
print(array)

[[17, 24, 1, 8, 15], [23, 5, 7, 14, 16], [4, 6, 13, 20, 22], [10, 12, 19, 21, 3], [11, 18, 25, 2, 9]]
[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]
[[  4  11 -12  -5   2]
 [ 10  -8  -6   1   3]
 [ -9  -7   0   7   9]
 [ -3  -1   6   8 -10]
 [ -2   5  12 -11  -4]]


### 7. Дано наступні матриці:
\begin{align}
A = \begin{bmatrix}
    1 & 24 & 1 & 8 & 15 \\
    -3 & 5 & 7 & -14 & 16 \\
    4 & 6 & -3 & 20 & 2 \\
    10 & 12 & 19 & 21 & 3 \\
    1 & 1 & 2 & -2 & 0 \\
\end{bmatrix}
\end{align}
\begin{align}
\end{align}
\begin{align}
B = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}
Знайти:

#### 7.1. Нормалізуйте: $(A B)^{-1}B$
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [40]:
string1 = "1 & 24 & 1 & 8 & 15 \\
    -3 & 5 & 7 & -14 & 16 \\
    4 & 6 & -3 & 20 & 2 \\
    10 & 12 & 19 & 21 & 3 \\
    1 & 1 & 2 & -2 & 0 \\"
string2 = "17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\"
matrix_list1 = string_to_list(string1)
matrix_list2 = string_to_list(string2)

matrix1 = np.array(matrix_list1)
matrix2 = np.array(matrix_list2)
AB = np.multiply(matrix1,matrix2)
print(AB)
flip_AB = np

[[1, 24, 1, 8, 15], [-3, 5, 7, -14, 16], [4, 6, -3, 20, 2], [10, 12, 19, 21, 3], [1, 1, 2, -2, 0]]
[[17, 24, 1, 8, 15], [23, 5, 7, 14, 16], [4, 6, 13, 20, 22], [10, 12, 19, 21, 3], [11, 18, 25, 2, 9]]
[[  17  576    1   64  225]
 [ -69   25   49 -196  256]
 [  16   36  -39  400   44]
 [ 100  144  361  441    9]
 [  11   18   50   -4    0]]


#### 7.2. Змініть матрицю B таким чином, щоб всі елементи k, такі що 3 < k < 16, змінили знак.
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

### 8. Створіть випадковий вектор розміру 10 і замініть максимальне значення на 0
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 4хв
```

### Pandas

### 8. Розглянемо наступний словник ```data``` та список ```labels```:

In [2]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

#### 8.1. Створіть ```DataFrame``` ```df``` з даних словника ```data``` з індексами зі списку ```labels```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.2. Відобразіть базову інформацію про цей ```DataFrame``` та його дані:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.3. Поверніть перші 5 рядків ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.4. Виберіть стовпчики ```"animal"``` та ```"age"``` з ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.5 Виберіть дані з рядків ```[1, 5, 8]``` та стовпчиків ```['animal', 'age']```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.6. Виберіть лише ті рядки, в яких к-сть візитів більша ніж 3:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.7. Виберіть рядки, де вік відсутній, тобто ```NaN```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.8. Виберіть рядки з котами, вік яких більше ніж 2:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.9. Підрахуйте середній вік для кожного з типів тварин:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

#### 8.10. Відсортуйте ```df``` по-перше за віком в спадаючому порядку, по-друге за к-стю візитів в зростаючому порядку:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

#### 8.11. Стовпець "priority" містить значення "yes" та "no". Замінити цей стовпець стовпчиком булевих значень: "yes" на True, а "no" на False:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

## Scipy & Matplotlib

### 9. За допомогою scipy згенерувати та за допомогою matplotlib побудувати функцію розподілу ймовірностей для вибірок, правильно підписавши осі та назвавши графік з обраними відповідними параметрами:

#### 9.1. Для виібрки з нормально розподіленої випадкової величини:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.2. Для вибірки з розподілу Бернулі:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.3. Для вибірки з біноміального розподілу:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.4. Для вибірки з розподілу Пуассона:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```